Repository eunomia-bpf/eunomia.dev, pull requests merged in 2023-08, with the labels that each got.

#4 Add workflow for deployment
  .github/workflows/mkdocs.yml
  README.md
  docs/assets/icon.svg
  docs/tutorials/ChatGPT.zh.md
  docs/tutorials/SUMMARY.md
  docs/tutorials/SUMMARY.zh.md
  mkdocs.yaml
Labels: size/XXL

#5 fix homepage h1 text color in dark mode
  material/overrides/home.html
Labels: size/XS

#6 Update main.html for google analysis
  material/overrides/main.html
Labels: size/XS

#7 Fix navigation bar on small screen
  material/overrides/home.html
Labels: size/S

#8 Fix md footer position
  material/overrides/home.html
Labels: size/S

#9 Add CNAME file
  docs/CNAME
Labels: size/XS

#13 Fix deploy judgement
  .github/workflows/mkdocs.yml
Labels: size/XS

#14 Add makefile and gpttrace doc
  .github/workflows/mkdocs.yml
  .gitignore
  Makefile
  mkdocs.yaml
  rename.sh
Labels: size/M

#15 fix: deploy in push
  .github/workflows/mkdocs.yml
Labels: size/XS

#16 add other project page
  mkdocs.yaml
  others/bpf-benchmark.md
  others/bpf-compatible.md
  others/index.ms
  rename.sh
Labels: size/L

#17 Fix typo
  others/bpf-compatible.md
Labels: size/XS

#19 Rename Other-Projects tag
  mkdocs.yaml
Labels: size/XS
